name: Create new release

# triggered manually or if file version changes
on: 
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'fastHistory/config/default_version.txt'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get release version from version file
        run: |
            echo "FH_RELEASE_VERSION=$(cat $GITHUB_WORKSPACE/fastHistory/config/default_version.txt)" >> $GITHUB_ENV
      - name: Show version 
        run: echo $FH_RELEASE_VERSION
      - name: Create Github release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v$FH_RELEASE_VERSION 
          release_name: v$FH_RELEASE_VERSION 
          draft: false
          prerelease: false
